### ISSUE TITLE
'list index out of range' when exporting

### ISSUE THREAD

**Issue by Alvarocz** [FakeYou/mashed#1]
bpy.ops.object.select_all(action='TOGGLE')
Traceback (most recent call last):
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 1640, in execute
    ExportRenderware(context,  self.expVersion, self.filepath)
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 1610, in __init__
    outf.write(self.RpClump(context, exportVer).bin())
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 1571, in __init__
    self.R.RwFrame(self, object, None)
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 933, in __init__
    self.R.RwFrame(self.clump, child, self)
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 922, in __init__
    self.atomic = self.R.RpAtomic(self)
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 1011, in __init__
    self.geometry = self.R.RpGeometry(self)
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 1324, in __init__
    self.addBlenderPoly(poly)
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 1407, in addBlenderPoly
    self.addRawPoly([p.vertices[0], p.vertices[1], p.vertices[2]], [p.loop_indices[0], p.loop_indices[1], p.loop_indices[2]], p.material_index)
  File "/usr/share/blender/2.78/scripts/addons/io_scene_dff.py", line 1399, in addRawPoly
    self.matTris[mat].append(newIds[0])
IndexError: list index out of range

location: <unknown location>:-1

Note: The model doesn't contain materials.

**Comment by Alvarocz** [comment]
Solution found.
All objects must have at least one material assigned.
